### ISSUE TITLE
I can't withdrawal my sats from lntip bot on telegram

### ISSUE THREAD

**Issue by iamveritas** [LightningTipBot/LightningTipBot#510]
hi, no matter the amount I ask to be payed the bot fails to do it. what am I doing wrong? see below, the balance is 4478, and even if I try 4400 which is more than 1% less it sill fails.

<img width="1533" alt="image" src="https://github.com/user-attachments/assets/d6f863b6-687a-4f00-bcfc-47ac6daeef5d">

**Comment by callebtc** [comment]
Try less.
