### ISSUE TITLE
Decommissioned – LightningTipBot No Withdraw!

### ISSUE THREAD

**Issue by LTSpencer** [LightningTipBot/LightningTipBot#511]
**Calle Bro !
comon fix Withdraw pls!**
![image](https://github.com/user-attachments/assets/ff805085-b4f9-4f39-b524-9c831f90bf49)
![image](https://github.com/user-attachments/assets/06cffaf8-66af-458c-9ca0-3f7f8a3ca2cc)
Bot is down! Let me withdraw ... pls 
pay you 300$

**Comment by callebtc** [comment]
Working. Please contact me on Telegram if needed.
